version: '3.1'

services:
  postgres-test:
    restart: always
    image: 'postgres:10.4-alpine'
    env_file:
      - '.test_env'
    volumes:
      - 'ourchive-postgresql-test:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  website-test:
    build: .
    entrypoint: ["python", "manage.py","runserver"]
    env_file:
      - '.test_env'
    volumes:
      - '.:/ourchive'
    ports:
      - '5000:5000'

  redis-test:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - './redis-test:/var/lib/redis/data'
    ports:
      - '6379:6379'


volumes:
  ourchive-postgresql-test:
      external: true
  redis-test:
