"""empty message

Revision ID: 0c229dceffe7
Revises: ce51cec3eaa5
Create Date: 2018-03-10 11:59:44.284831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c229dceffe7'
down_revision = 'ce51cec3eaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark_links', sa.Column('text', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark_links', 'text')
    # ### end Alembic commands ###
