"""empty message

Revision ID: 11b135ee9f8e
Revises: 3664035a952b
Create Date: 2018-03-05 15:07:25.732252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b135ee9f8e'
down_revision = '3664035a952b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_to_comment',
    sa.Column('parent_comment_id', sa.Integer(), nullable=False),
    sa.Column('child_comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('parent_comment_id', 'child_comment_id')
    )
    op.add_column('chapters', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'summary')
    op.drop_table('comment_to_comment')
    # ### end Alembic commands ###
