"""empty message

Revision ID: 215d36f45c72
Revises: 1d8117d6ed14
Create Date: 2018-03-25 17:46:55.327351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215d36f45c72'
down_revision = '1d8117d6ed14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
