"""empty message

Revision ID: 28c51d215b39
Revises: b818a20d5ee1
Create Date: 2018-04-14 22:44:02.690566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c51d215b39'
down_revision = 'b818a20d5ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapters_work_id_fkey', 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'works', ['work_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key('chapters_work_id_fkey', 'chapters', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###
