"""empty message

Revision ID: 493466ec9210
Revises: b7afce71bc6f
Create Date: 2018-04-16 21:36:46.761078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493466ec9210'
down_revision = 'b7afce71bc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chapters', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('works', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('works', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'updated_on')
    op.drop_column('works', 'created_on')
    op.drop_column('chapters', 'updated_on')
    op.drop_column('chapters', 'created_on')
    # ### end Alembic commands ###
