"""empty message

Revision ID: 5a2f233515c0
Revises: ffd7cedf0bf5
Create Date: 2018-10-22 20:00:00.281840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2f233515c0'
down_revision = 'ffd7cedf0bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('audio_length', sa.BigInteger(), nullable=True))
    op.add_column('chapters', sa.Column('image_format', sa.String(), nullable=True))
    op.add_column('chapters', sa.Column('image_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'image_size')
    op.drop_column('chapters', 'image_format')
    op.drop_column('chapters', 'audio_length')
    # ### end Alembic commands ###
