"""empty message

Revision ID: 615a7420219b
Revises: 5a2f233515c0
Create Date: 2018-10-25 18:58:50.529511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615a7420219b'
down_revision = '5a2f233515c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('anon_comments_permitted', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('anon_comments_permitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'anon_comments_permitted')
    op.drop_column('bookmarks', 'anon_comments_permitted')
    # ### end Alembic commands ###
