"""empty message

Revision ID: 6f2102d97993
Revises: bcce035c4d07
Create Date: 2018-03-10 12:21:37.082185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2102d97993'
down_revision = 'bcce035c4d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark_comments')
    op.add_column('comments', sa.Column('bookmark_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'bookmarks', ['bookmark_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'bookmark_id')
    op.create_table('bookmark_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bookmark_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], name='bookmark_comments_bookmark_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bookmark_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookmark_comments_pkey')
    )
    # ### end Alembic commands ###
