"""empty message

Revision ID: 86836163e180
Revises: 615a7420219b
Create Date: 2018-10-25 19:47:01.301440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86836163e180'
down_revision = '615a7420219b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('comments_permitted', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('comments_permitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'comments_permitted')
    op.drop_column('bookmarks', 'comments_permitted')
    # ### end Alembic commands ###
