"""empty message

Revision ID: 89989d88f652
Revises: 5be791481595
Create Date: 2018-05-13 22:15:19.173764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89989d88f652'
down_revision = '5be791481595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
