"""empty message

Revision ID: b818a20d5ee1
Revises: 1d6ddbd971e5
Create Date: 2018-04-14 22:39:03.373013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b818a20d5ee1'
down_revision = '1d6ddbd971e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapters_work_id_fkey', 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'works', ['work_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key('chapters_work_id_fkey', 'chapters', 'works', ['work_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
