"""empty message

Revision ID: d661f880496c
Revises: 86836163e180
Create Date: 2018-10-31 00:58:56.041382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd661f880496c'
down_revision = '86836163e180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('process_status', sa.Integer(), nullable=True))
    op.add_column('works', sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'uid')
    op.drop_column('works', 'process_status')
    # ### end Alembic commands ###
