"""empty message

Revision ID: de35abfdeb73
Revises: d661f880496c
Create Date: 2018-11-03 03:30:49.742439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de35abfdeb73'
down_revision = 'd661f880496c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('epub_id', sa.String(), nullable=True))
    op.add_column('works', sa.Column('zip_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'zip_id')
    op.drop_column('works', 'epub_id')
    # ### end Alembic commands ###
