"""empty message

Revision ID: f1fabccfa03d
Revises: 0c229dceffe7
Create Date: 2018-03-10 12:15:20.060138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fabccfa03d'
down_revision = '0c229dceffe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('bookmark_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'bookmarks', ['bookmark_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'bookmark_id')
    # ### end Alembic commands ###
