"""empty message

Revision ID: ffd7cedf0bf5
Revises: db6a057f5865
Create Date: 2018-10-15 00:22:54.012044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd7cedf0bf5'
down_revision = 'db6a057f5865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('cover_alt_text', sa.String(), nullable=True))
    op.add_column('works', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'cover_url')
    op.drop_column('works', 'cover_alt_text')
    # ### end Alembic commands ###
