"""empty message

Revision ID: fffeae1bb48c
Revises: 55585c569f52
Create Date: 2018-03-02 16:58:59.159175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffeae1bb48c'
down_revision = '55585c569f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('work_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'work_notes')
    # ### end Alembic commands ###
